### ISSUE TITLE
Remove `rgdal` immediately

### ISSUE THREAD

**Issue by rsbivand** [redworld123/CoastlineFD#1]
@redworld123  As you should have noticed from the verbose startup messages from `sp` and `rgdal`, `rgdal` (and `rgeos`, `maptoools`) will be archived in about six weeks https://r-spatial.github.io/evolution/. You must remove `rgdal` from imports ASAP; you already impport `sf`, so the retiring packages is completely uneccessary.

**Comment by rsbivand** [comment]
And note two errors in https://cran.r-project.org/web/checks/check_results_CoastlineFD.html for trying to write elsewhere than a temporary directory.

**Comment by redworld123** [comment]
Sorry for the late reply. The vector data processed by my R package is a kind of compacted line element. If the sf package function is used to read the vector data directly, an error will be reported. Of course, I am also looking for further reasons for the error in the paper and hope to resolve the problem this morning.

**Comment by redworld123** [comment]
I have tried to resolve two errors in Debian systems by prohibiting them from exporting xlsx files in a read-only location.

**Comment by rsbivand** [comment]
@redworld123 R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by redworld123** [comment]
I successfully deleted sp, rgdal, and maptools packages, and fortunately found a way to solve the problem that sf packages would report errors reading compact vector files directly.

**Comment by rsbivand** [comment]
@redworld123 Thanks for your cooperation!
